Revert "Mark the current BUILD_* warnings as errors by default"
* This allows BUILD_BROKEN_USES_BUILD_COPY_HEADERS to be used without resulting in compilation errors like: error: BUILD_COPY_HEADERS is obsolete

This reverts commit c4bdff5f7e8d0f60e7084cb83abe759fb3b65363.